version: '3'
services:
  postgres:
    container_name: postgres_container
    image: postgres:12.4
    restart: always
    volumes:
      - ${PWD}/postgres:/var/lib/postgresql/data
    ports:
    - "5432:5432"
    environment:
    - POSTGRES_USER=data
    - POSTGRES_PASSWORD=data
    - POSTGRES_DB=data
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: data@mail.ru
      PGADMIN_DEFAULT_PASSWORD: data
    ports:
      - "5050:80"
  redis:
    container_name: myredis
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
